# Cargando los datos

In [74]:
import numpy as np
import pandas as pd

sales=pd.read_csv('FACT_SALES.csv')
category=pd.read_csv('DIM_CATEGORY.csv')
calendar=pd.read_excel('DIM_CALENDAR.xlsx')
product=pd.read_excel('DIM_PRODUCT.xlsx')
segment=pd.read_excel('DIM_SEGMENT.xlsx')

# Vista general de los datos

In [75]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   WEEK                         122002 non-null  object
 1   ITEM_CODE                    122002 non-null  object
 2   TOTAL_UNIT_SALES             122002 non-null  float64
 3   TOTAL_VALUE_SALES            122002 non-null  float64
 4   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 5   REGION                       122002 non-null  object
dtypes: float64(3), object(3)
memory usage: 5.6+ MB

In [76]:
sales.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5

Vemos que el DataFrame sales representa las ventas de diversos productos por cada semana

In [77]:
category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_CATEGORY  5 non-null      int64
 1   CATEGORY     5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [78]:
category.head()

   ID_CATEGORY                        CATEGORY
0            1  FABRIC TREATMENT and SANIT\r\n
1            2                       AIR CARE
2            3                    LAVAVAJILLAS
3            4                MEGA SUPERFICIES
4            5             LAVATORY CARE & BRC

Este Dataframe parece indicar el significado del ID, correspondiendo a una categoría de producto

In [79]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 6.2+ KB

In [ ]:
calendar.head()

    WEEK  YEAR  MONTH  WEEK_NUMBER       DATE
0  01-21  2021      1            1 2021-01-10
1  02-21  2021      1            2 2021-01-17
2  03-21  2021      1            3 2021-01-24
3  04-21  2021      1            4 2021-01-31
4  05-21  2021      2            5 2021-02-07

El DataFrame calendar indica qué semana corresponde a cada fecha, mes y año. Las fechas en la columna DATE ya están en el formato correcto.

In [81]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              503 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

In [82]:
product.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

Este dataframe da más detalles de cada producto

In [83]:
segment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     object
 2   ATTR2     53 non-null     object
 3   ATTR3     52 non-null     object
 4   FORMAT    53 non-null     object
 5   SEGMENT   53 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.6+ KB

In [84]:
segment.head()

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO  BLEACH
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO  BLEACH
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO  BLEACH
3         1  CLORO  CLORO  MULTIUSOS      GEL  BLEACH
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO  BLEACH

In [85]:
segment['SEGMENT'].unique()

array(['BLEACH', 'LIQUID & GEL', 'POWDER', 'OTHERS', 'PRETREAT', 'BAR',
       'SANITIZER'], dtype=object)

Este DataFrame indica el segmento correspondiente a la categoría y atributos del producto

# Limpieaza de Datos

Parece que la primera categoría del dataframe category tiene caracteres extra: "\r\n"

In [86]:
category.loc[0,'CATEGORY']='FABRIC TREATMENT and SANIT'
category.head()

   ID_CATEGORY                    CATEGORY
0            1  FABRIC TREATMENT and SANIT
1            2                   AIR CARE
2            3                LAVAVAJILLAS
3            4            MEGA SUPERFICIES
4            5         LAVATORY CARE & BRC

Los DataFrame "product" y "segment" tiene datos nulos.

## PRODUCT

In [87]:
product[product['ITEM'].isna()]

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS

En este caso, no conviene eliminar estas filas porque representan productos con una descripción completa más allá de su código de ITEM. Lo normal sería preguntar a la compañía por el código de estos productos, pero como no es posible, colocaré unos códigos por mi cuenta

In [88]:
product.iloc[500:505]

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
500,RECKITT,VANISH,7501058789778BP1,VANISH EXT HIGIENE REM MANCHAS GAL 4LT + VANIS...,1,LIQUIDO,SAFE BLEACH,FABRIC TREATMENT,ROSA
501,INDS. ALEN,CLORALEX,7501025412142,CLORALEX AROMAS BLANQUEADOR C/AROMA LAVANDA GA...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
502,INDS. ALEN,CLORALEX,NaN,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,NaN,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS
504,CLOROX,CLOROX,7502240948188BP1,CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

Vemos que los códigos no tienen una estructura concreta, entonces propondré los siguientes códigos: '0000000000001' y '0000000000002', pero primero hay que checar que estos códigos no estén ya en la columna ITEM, porque deben de ser códigos únicos

In [89]:
print('0000000000001' in product['ITEM'])
print('0000000000002' in product['ITEM'])

False
False

Dado que no están repetidos, podemos asignarlos a los productos

In [90]:
product.iloc[502]=product.iloc[502].replace(np.nan,'0000000000001')
product.iloc[503]=product.iloc[503].replace(np.nan,'0000000000002')

In [91]:
product.iloc[502:504]

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
502,INDS. ALEN,CLORALEX,0000000000001,CLORALEX EL RENDIDOR BOT PLAST 2LT,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
503,CLOROX,CLOROX,0000000000002,CLOROX MASCOTAS BLANQUEADOR+DETERGENTE GALON 10L,1,LIQUIDO,CLORO,CLORO,MASCOTAS

In [92]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              505 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

Todavía falta manejar los datos nulos en las columnas ATTR1 y ATTR3, pero hemos visto anteriormente que cuando no hay cierto atributo, es colocado como "NO DEFINIDO", por lo que esos valores nulos podemos reemplazarlos con ese mismo formato

In [93]:
product.replace(np.nan,"NO DEFINIDO",inplace=True)

In [94]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              505 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             505 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             505 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

## SEGMENT

In [95]:
segment[segment['ATTR3'].isna()]

    CATEGORY  ATTR1  ATTR2 ATTR3   FORMAT SEGMENT
10         1  CLORO  CLORO   NaN  LIQUIDO  BLEACH

Esta es la única fila que contiene un dato nulo y es igual un atributo, por lo que podemos aplicar el mismo método de antes

In [96]:
segment.replace(np.nan,"NO DEFINIDO",inplace=True)

In [97]:
segment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     object
 2   ATTR2     53 non-null     object
 3   ATTR3     53 non-null     object
 4   FORMAT    53 non-null     object
 5   SEGMENT   53 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.6+ KB

## Hay datos duplicados?

In [98]:
#La función duplicated() regresa un df en el que si el dato está duplicado regresa True, pero si no es duplicado, regresa False
print('Duplicados en sales:', sum(sales.duplicated())) #Al sumar los valores booleanos, si todos son falsos, la suma será 0 (que es lo ideal)
print('Duplicados en category:', sum(category.duplicated()))
print('Duplicados en calendar:', sum(calendar.duplicated()))
print('Duplicados en product:', sum(product.duplicated()))
print('Duplicados en segment:', sum(segment.duplicated()))

Duplicados en sales: 0
Duplicados en category: 0
Duplicados en calendar: 0
Duplicados en product: 0
Duplicados en segment: 1

Hay un duplicado en segment

In [99]:
segment=segment[~segment.duplicated()] #~segment.duplicated() es el NOT de la función duplicated
print('Duplicados en segment:', sum(segment.duplicated()))

Duplicados en segment: 0

# Unión de DataFrames

In [100]:
df=sales.copy() #El dataframe unido será guardado en la variable df, en base a las ventas
df.head()

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5

Podemos cambiar la columna de WEEK por una fecha con formato estandarizado, las cuales se encuentran en el DataFrame calendar

In [101]:
dates=calendar[['WEEK','DATE']]
dates.head()

    WEEK       DATE
0  01-21 2021-01-10
1  02-21 2021-01-17
2  03-21 2021-01-24
3  04-21 2021-01-31
4  05-21 2021-02-07

In [102]:
def df_dict(dataframe,keys,values):
    dic={}
    for i in range(len(dataframe)):
        dic.update({dataframe.iloc[i][keys]: dataframe.iloc[i][values]}) 
    return dic

week_to_date=df_dict(dates,keys='WEEK',values='DATE') #Creating a dictionary where the keys are the weeks and the values are the dates
week_to_date

{'01-21': Timestamp('2021-01-10 00:00:00'),
 '02-21': Timestamp('2021-01-17 00:00:00'),
 '03-21': Timestamp('2021-01-24 00:00:00'),
 '04-21': Timestamp('2021-01-31 00:00:00'),
 '05-21': Timestamp('2021-02-07 00:00:00'),
 '06-21': Timestamp('2021-02-14 00:00:00'),
 '07-21': Timestamp('2021-02-21 00:00:00'),
 '08-21': Timestamp('2021-02-28 00:00:00'),
 '09-21': Timestamp('2021-03-07 00:00:00'),
 '10-21': Timestamp('2021-03-14 00:00:00'),
 '11-21': Timestamp('2021-03-21 00:00:00'),
 '12-21': Timestamp('2021-03-28 00:00:00'),
 '13-21': Timestamp('2021-04-04 00:00:00'),
 '14-21': Timestamp('2021-04-11 00:00:00'),
 '15-21': Timestamp('2021-04-18 00:00:00'),
 '16-21': Timestamp('2021-04-25 00:00:00'),
 '17-21': Timestamp('2021-05-02 00:00:00'),
 '18-21': Timestamp('2021-05-09 00:00:00'),
 '19-21': Timestamp('2021-05-16 00:00:00'),
 '20-21': Timestamp('2021-05-23 00:00:00'),
 '21-21': Timestamp('2021-05-30 00:00:00'),
 '22-21': Timestamp('2021-06-06 00:00:00'),
 '23-21': Timestamp('2021-06-13 00:00:00'),
 '24-21': Timestamp('2021-06-20 00:00:00'),
 '25-21': Timestamp('2021-06-27 00:00:00'),
 '26-21': Timestamp('2021-07-04 00:00:00'),
 '27-21': Timestamp('2021-07-11 00:00:00'),
 '28-21': Timestamp('2021-07-18 00:00:00'),
 '29-21': Timestamp('2021-07-25 00:00:00'),
 '30-21': Timestamp('2021-08-01 00:00:00'),
 '31-21': Timestamp('2021-08-08 00:00:00'),
 '32-21': Timestamp('2021-08-15 00:00:00'),
 '33-21': Timestamp('2021-08-22 00:00:00'),
 '34-21': Timestamp('2021-08-29 00:00:00'),
 '35-21': Timestamp('2021-09-05 00:00:00'),
 '36-21': Timestamp('2021-09-12 00:00:00'),
 '37-21': Timestamp('2021-09-19 00:00:00'),
 '38-21': Timestamp('2021-09-26 00:00:00'),
 '39-21': Timestamp('2021-10-03 00:00:00'),
 '40-21': Timestamp('2021-10-10 00:00:00'),
 '41-21': Timestamp('2021-10-17 00:00:00'),
 '42-21': Timestamp('2021-10-24 00:00:00'),
 '43-21': Timestamp('2021-10-31 00:00:00'),
 '44-21': Timestamp('2021-11-07 00:00:00'),
 '45-21': Timestamp('2021-11-14 00:00:00'),
 '46-21': Timestamp('2021-11-21 00:00:00'),
 '47-21': Timestamp('2021-11-28 00:00:00'),
 '48-21': Timestamp('2021-12-05 00:00:00'),
 '49-21': Timestamp('2021-12-12 00:00:00'),
 '50-21': Timestamp('2021-12-19 00:00:00'),
 '51-21': Timestamp('2021-12-26 00:00:00'),
 '52-21': Timestamp('2022-01-02 00:00:00'),
 '01-22': Timestamp('2022-01-09 00:00:00'),
 '02-22': Timestamp('2022-01-16 00:00:00'),
 '03-22': Timestamp('2022-01-23 00:00:00'),
 '04-22': Timestamp('2022-01-30 00:00:00'),
 '05-22': Timestamp('2022-02-06 00:00:00'),
 '06-22': Timestamp('2022-02-13 00:00:00'),
 '07-22': Timestamp('2022-02-20 00:00:00'),
 '08-22': Timestamp('2022-02-27 00:00:00'),
 '09-22': Timestamp('2022-03-06 00:00:00'),
 '10-22': Timestamp('2022-03-13 00:00:00'),
 '11-22': Timestamp('2022-03-20 00:00:00'),
 '12-22': Timestamp('2022-03-27 00:00:00'),
 '13-22': Timestamp('2022-04-03 00:00:00'),
 '14-22': Timestamp('2022-04-10 00:00:00'),
 '15-22': Timestamp('2022-04-17 00:00:00'),
 '16-22': Timestamp('2022-04-24 00:00:00'),
 '17-22': Timestamp('2022-05-01 00:00:00'),
 '18-22': Timestamp('2022-05-08 00:00:00'),
 '19-22': Timestamp('2022-05-15 00:00:00'),
 '20-22': Timestamp('2022-05-22 00:00:00'),
 '21-22': Timestamp('2022-05-29 00:00:00'),
 '22-22': Timestamp('2022-06-05 00:00:00'),
 '23-22': Timestamp('2022-06-12 00:00:00'),
 '24-22': Timestamp('2022-06-19 00:00:00'),
 '25-22': Timestamp('2022-06-26 00:00:00'),
 '26-22': Timestamp('2022-07-03 00:00:00'),
 '27-22': Timestamp('2022-07-10 00:00:00'),
 '28-22': Timestamp('2022-07-17 00:00:00'),
 '29-22': Timestamp('2022-07-24 00:00:00'),
 '30-22': Timestamp('2022-07-31 00:00:00'),
 '31-22': Timestamp('2022-08-07 00:00:00'),
 '32-22': Timestamp('2022-08-14 00:00:00'),
 '33-22': Timestamp('2022-08-21 00:00:00'),
 '34-22': Timestamp('2022-08-28 00:00:00'),
 '35-22': Timestamp('2022-09-04 00:00:00'),
 '36-22': Timestamp('2022-09-11 00:00:00'),
 '37-22': Timestamp('2022-09-18 00:00:00'),
 '38-22': Timestamp('2022-09-25 00:00:00'),
 '39-22': Timestamp('2022-10-02 00:00:00'),
 '40-22': Timestamp('2022-10-09 00:00:00'),
 '41-22': Timestamp('2022-10-16 00:00:00'),
 '42-22': Timestamp('2022-10-23 00:00:00'),
 '43-22': Timestamp('2022-10-30 00:00:00'),
 '44-22': Timestamp('2022-11-06 00:00:00'),
 '45-22': Timestamp('2022-11-13 00:00:00'),
 '46-22': Timestamp('2022-11-20 00:00:00'),
 '47-22': Timestamp('2022-11-27 00:00:00'),
 '48-22': Timestamp('2022-12-04 00:00:00'),
 '49-22': Timestamp('2022-12-11 00:00:00'),
 '50-22': Timestamp('2022-12-18 00:00:00'),
 '51-22': Timestamp('2022-12-25 00:00:00'),
 '52-22': Timestamp('2023-01-01 00:00:00'),
 '01-23': Timestamp('2023-01-09 00:00:00'),
 '02-23': Timestamp('2023-01-16 00:00:00'),
 '03-23': Timestamp('2023-01-23 00:00:00'),
 '04-23': Timestamp('2023-01-30 00:00:00'),
 '05-23': Timestamp('2023-02-06 00:00:00'),
 '06-23': Timestamp('2023-02-13 00:00:00'),
 '07-23': Timestamp('2023-02-20 00:00:00'),
 '08-23': Timestamp('2023-02-27 00:00:00'),
 '09-23': Timestamp('2023-03-06 00:00:00'),
 '10-23': Timestamp('2023-03-13 00:00:00'),
 '11-23': Timestamp('2023-03-20 00:00:00'),
 '12-23': Timestamp('2023-03-27 00:00:00'),
 '13-23': Timestamp('2023-04-03 00:00:00'),
 '14-23': Timestamp('2023-04-10 00:00:00'),
 '15-23': Timestamp('2023-04-17 00:00:00'),
 '16-23': Timestamp('2023-04-24 00:00:00'),
 '17-23': Timestamp('2023-05-01 00:00:00'),
 '18-23': Timestamp('2023-05-08 00:00:00'),
 '19-23': Timestamp('2023-05-15 00:00:00'),
 '20-23': Timestamp('2023-05-22 00:00:00'),
 '21-23': Timestamp('2023-05-29 00:00:00'),
 '22-23': Timestamp('2023-06-05 00:00:00'),
 '23-23': Timestamp('2023-06-12 00:00:00'),
 '24-23': Timestamp('2023-06-19 00:00:00'),
 '25-23': Timestamp('2023-06-26 00:00:00'),
 '26-23': Timestamp('2023-07-03 00:00:00'),
 '27-23': Timestamp('2023-07-10 00:00:00'),
 '28-23': Timestamp('2023-07-17 00:00:00'),
 '29-23': Timestamp('2023-07-24 00:00:00'),
 '30-23': Timestamp('2023-07-31 00:00:00'),
 '31-23': Timestamp('2023-08-07 00:00:00'),
 '32-23': Timestamp('2023-08-14 00:00:00'),
 '33-23': Timestamp('2023-08-21 00:00:00'),
 '34-23': Timestamp('2023-08-28 00:00:00'),
 '35-23': Timestamp('2023-09-04 00:00:00'),
 '36-23': Timestamp('2023-09-11 00:00:00'),
 '37-23': Timestamp('2023-09-18 00:00:00'),
 '38-23': Timestamp('2023-09-25 00:00:00'),
 '39-23': Timestamp('2023-10-02 00:00:00'),
 '40-23': Timestamp('2023-10-09 00:00:00'),
 '41-23': Timestamp('2023-10-16 00:00:00'),
 '42-23': Timestamp('2023-10-23 00:00:00'),
 '43-23': Timestamp('2023-10-30 00:00:00'),
 '44-23': Timestamp('2023-11-06 00:00:00'),
 '45-23': Timestamp('2023-11-13 00:00:00'),
 '46-23': Timestamp('2023-11-20 00:00:00'),
 '47-23': Timestamp('2023-11-27 00:00:00'),
 '48-23': Timestamp('2023-12-04 00:00:00'),
 '49-23': Timestamp('2023-12-11 00:00:00'),
 '50-23': Timestamp('2023-12-18 00:00:00'),
 '51-23': Timestamp('2023-12-25 00:00:00'),
 '52-23': Timestamp('2024-01-01 00:00:00')}

In [103]:
week_sales=df['WEEK'].unique() #Estas son las únicas semanas que aparecen en las ventas
for week in week_sales:
    df.replace(week,week_to_date[week],inplace=True)
df.head()

C:\Users\sorak\AppData\Local\Temp\ipykernel_3024\1056086798.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(week,week_to_date[week],inplace=True)

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION
0,2022-08-28,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5
1,2022-08-28,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5
2,2022-08-28,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5
3,2022-08-28,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5
4,2022-08-28,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5

El siguiente paso es juntar los dataframes de category y segment en el de product

Primero, anexaremos la columna de SEGMENT a product en base a lo indicado en el dataframe segment

In [104]:
segment.head()

   CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT SEGMENT
0         1  CLORO  CLORO    BAMBINO  LIQUIDO  BLEACH
1         1  CLORO  CLORO  GERMICIDA  LIQUIDO  BLEACH
2         1  CLORO  CLORO   MASCOTAS  LIQUIDO  BLEACH
3         1  CLORO  CLORO  MULTIUSOS      GEL  BLEACH
4         1  CLORO  CLORO  MULTIUSOS  LIQUIDO  BLEACH

La columna SEGMENT depende de las columnas CATEGORY, ATTR1, ATTR2, ATTR3, FORMAT

In [105]:
product=product.merge(segment, on=['CATEGORY','ATTR1','ATTR2','ATTR3','FORMAT'], validate='m:1') #Con la función merge, puedo juntar ambos dataframes en base a la columnas mencionadas de segment
product.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,SEGMENT
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH

Ahora, juntamos product con category, reemplazando la columna de CATEGORY con el significado colocado en category

In [106]:
category.head()

   ID_CATEGORY                    CATEGORY
0            1  FABRIC TREATMENT and SANIT
1            2                   AIR CARE
2            3                LAVAVAJILLAS
3            4            MEGA SUPERFICIES
4            5         LAVATORY CARE & BRC

In [107]:
id_to_category=df_dict(category,'ID_CATEGORY','CATEGORY') #Creating a dictionary where the keys are the ID and the values are the categories

for id in id_to_category.keys():
    product.replace(id,id_to_category[id],inplace=True)
product.head()

,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,SEGMENT
0,INDS. ALEN,CLORALEX,0000075000592,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,FABRIC TREATMENT and SANIT,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
1,INDS. ALEN,CLORALEX,0000075000608,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,FABRIC TREATMENT and SANIT,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
2,INDS. ALEN,CLORALEX,0000075000615,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,FABRIC TREATMENT and SANIT,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
3,INDS. ALEN,CLORALEX,0000075000622,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,FABRIC TREATMENT and SANIT,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH
4,INDS. ALEN,CLORALEX,0000075000639,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,FABRIC TREATMENT and SANIT,LIQUIDO,CLORO,CLORO,NO DEFINIDO,BLEACH

# ANTES DE HACER EL MERGE, MEJOR JUNTAR PRIMERO JUNTAR EL DATAFRAME PRODUCT CON CATEGORY Y SEGMENT 
## podria generar como funcion lo de crear el diccionario y aplicarlo para las categorías

El siguiente paso es relacionar los ITEM_CODE con los códigos en la columna ITEM del dataframe product

In [108]:
product.rename(columns={'ITEM':'ITEM_CODE'},inplace=True) #cambiamos el nombre de la columna para que coincida con el de la columna del df
df=df.merge(product, on='ITEM_CODE') #Con la función merge, puedo juntar ambos dataframes en base a la columna ITEM_CODE

In [109]:
df

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,SEGMENT
0,2022-08-28,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
1,2022-08-28,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
2,2022-08-28,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
3,2022-08-28,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
4,2022-08-28,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,2023-07-03,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,VANISHOXIACTIONROSABOTE900GR+MMCRYSTALWHITEDOY...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
121998,2023-07-03,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,VANISH PODER O2 PRE-LAVADOR BOT.ATOM. 650 ML N...,FABRIC TREATMENT and SANIT,LIQUIDO,PRELAVADOR,FABRIC TREATMENT,ROSA,PRETREAT
121999,2023-07-03,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,VANISH PODER O2 DOYPACK 120 GR 7501058753441,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
122000,2023-07-03,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,VANISH PODER 02 INTELIGENCE SIN CLORO SOBRE 30...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER
122001,2023-07-03,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,VANISH PODER 02 INTELLIGENCE POLVO BOT 900 GR ...,FABRIC TREATMENT and SANIT,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,POWDER

In [110]:
df.to_csv('Final_DataFrame.csv')